version: '2.1'
services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c 'hugo -d /usr/share/html/ && hugo server -b http://localhost:1313 --bind=0.0.0.0'
    ports:
      - 1313:1313
    volumes:
      - ./site:/usr/share/blog
      - ./html:/usr/share/html
